### ISSUE TITLE
Ploomber's creator: Any feedback?

### ISSUE THREAD

**Issue by edublancas** [bhundt/COVID19#1]
Hi, I noticed you're using Ploomber. Thanks a lot! Do you have any feedback for us? Please share it here or let us know in our [Slack](https://ploomber.io/community) community.

**Comment by bhundt** [comment]
Thanks for developing ploomber!! I really like how lightweight it is....currently very happy. I will use it for some more projects and let you know when I stumble upon something which I think is worth discussing.
